#!/bin/bash
set -e

# set cross compile flags for macos
if [ "$(uname)" = "Darwin" ]; then
    # Homebrew uses a different install directory on x86_64 macs
    # So we need to jump through some hoops to make this work for both aarch64 and x86_64
    HOMEBREW="/opt/homebrew"
    if [ "$(uname -m)" = "x86_64" ]; then
        homebrew_base="/usr/local"
    fi

    export PATH="$HOMEBREW/opt/llvm/bin:$PATH"
    export LDFLAGS="-L$HOMEBREW/opt/llvm/lib"
    export CPPFLAGS="-I$HOMEBREW/opt/llvm/include"
    
    export TARGET_CC=$(which clang)
    export CC_X86_64_UNKNOWN_LINUX_GNU=x86_64-unknown-linux-gnu-gcc
    export CXX_X86_64_UNKNOWN_LINUX_GNU=x86_64-unknown-linux-gnu-g++
    export AR_X86_64_UNKNOWN_LINUX_GNU=x86_64-unknown-linux-gnu-ar
    export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc


    # Set cross compilation flags for alsa.
    export PKG_CONFIG_PATH="$HOMEBREW/Cellar/x86_64-unknown-linux-gnu-alsa-lib/1.2.10/lib/x86_64-unknown-linux-gnu/pkgconfig"
    export PKG_CONFIG_LIB_DIR="$HOMEBREW/Cellar/x86_64-unknown-linux-gnu-alsa-lib/1.2.10/lib/"
    export PKG_CONFIG_ALLOW_CROSS=1
fi

# pass all arguments to sindri
cargo run -r -p sindri -- $@
