name: Install deps
description: Install needed Ubuntu dependencies
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y -qq libasound2-dev
      shell: bash
